spring:
  application:
    name: app-bpm
  datasource:
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 1

server:
  port : 8082

camunda:
  bpm:
    history-level: FULL
    filter:
      create: show all
    admin-user:
      id: demo
      password: demo
      firstName: Demo
    default-serialization-format: application/json
    database:
      schema-update: create-drop
    job-execution:
      core-pool-size: 10
      deployment-aware: true
      max-jobs-per-acquisition: 3
      max-pool-size: 10
      queue-capacity: 3
    generic-properties:
      properties:
        enable-exceptions-after-unhandled-bpmn-error: true

incomingService:
  soapCallUrl: /services/accounts

service:
  account:
    endpoint: /ws-endpoint
    user: user
    password: pswd
  maaendern:
    endpoint: http://localhost:8089/maaendern
    user: user
    password: pswd
  vsnraendern:
    endpoint: http://localhost:8089/ma/{vsnr}
    user: user
    password: pswd

logging:
  level:
    de.hello: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  de:
    request:
      in: true
      out: true
      excludeUrls: /pingpong
